
export const REMOVE_TASK = 'REMOVE_TASK';
export const REMOVE_TASK_FAILURE = 'REMOVE_TASK_FAILURE';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';

export const FETCH_TASK = 'FETCH_TASK';
export const RECEIVE_TASK_SUCCESS = 'RECEIVE_TASK_SUCCESS';
export const RECEIVE_TASK_FAILURE = 'RECEIVE_TASK_FAILURE';

export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';

export const CHANGE_SEARCH = 'CHANGE_SEARCH'